---
- name: Update Docker container configuration
  become: yes
  collections:
    - community.docker
  vars:
     dockerContainerName: _dockerContainerName_
     dockerImageName: _dockerImageName_
  tasks:
    - name: Stop the Docker container
      community.docker.docker_container:
        name: {{ dockerContainerName }}
        state: stopped

    - name: Remove the Docker container
      community.docker.docker_container:
        name: {{ dockerContainerName }}
        state: absent

    - name: Recreate the Docker container with new configuration
      community.docker.docker_container:
        name: {{ dockerContainerName }}
        image: {{ dockerImageName }}:78
        state: started
        env:
          ENV_VAR1: new_value1
          ENV_VAR2: new_value2
        ports:
          - "8080:80"