apiVersion: v1

kind: Service

metadata:

  name: java-deploy

spec:
  type: ClusterIP
  ports:

  - port: 6379

  selector:

    app: java-deploy

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: java-deploy
  labels:
    app: java-deploy
spec:

  replicas: 1
  selector:
    matchLabels:
      app: java-deploy
  template:

    metadata:

      labels:

        app: java-deploy

    spec:

      containers:

      - name: java-deploy

        image: anand2993/javamavenimage

        ports:

        - containerPort: 6379

          name: java-deploy